### ISSUE TITLE
[친구찾기] 친구찾기 페이지 뷰 구현

### ISSUE THREAD

**Issue by lizuAg** [TeamDeli/Deli-Front#4]
## 문제 상황
> 친구찾기 페이지 뷰 구현하기

## 진행 상황
- [x] 컴포넌트 배치하기
- [x] 컴포넌트 수정하기(calendar -> 친구찾기 버튼으로..)

**Comment by kiiiyeon** [comment]
굿 넘잘했습니다!!!🥰 주은아 오른쪽에 Assignees랑 Labels 보이면 채워주세요!!!
